package org.gensokyo.plugin.easydoc.plan;

import org.apache.commons.lang3.StringUtils;

import java.util.HashSet;
import java.util.Set;
import java.util.regex.Pattern;

public final class PlanValidator {
    private static final Pattern VARIABLE_NAME_PATTERN = Pattern.compile("[a-zA-Z_][a-zA-Z0-9_]*");

    private PlanValidator() {
        throw new UnsupportedOperationException();
    }

    public static PlanValidationResult validateAndNormalize(DocPlan plan) {
        PlanValidationResult result = PlanValidationResult.ok();
        if (plan == null || plan.getRoots() == null) {
            return result;
        }
        Set<String> seen = new HashSet<>();
        for (DocNode node : plan.getRoots()) {
            validateNode(node, seen, result);
        }
        return result;
    }

    private static void validateNode(DocNode node, Set<String> seen, PlanValidationResult result) {
        if (node == null) {
            return;
        }
        String defaultVariable = DocPlanBuilder.defaultVariableName(node.getType(), node.getDisplayName());
        boolean autoGeneratedCandidate = StringUtils.isBlank(node.getVariableName())
                || StringUtils.equals(node.getVariableName(), defaultVariable);
        if (StringUtils.isBlank(node.getVariableName())) {
            node.setVariableName(defaultVariable);
        }
        String variable = StringUtils.trimToEmpty(node.getVariableName());
        node.setVariableName(variable);
        if (!VARIABLE_NAME_PATTERN.matcher(variable).matches()) {
            result.addError("Invalid variable name: " + variable + " (" + node.getDisplayName() + ")");
        } else if (!seen.add(variable)) {
            if (autoGeneratedCandidate) {
                variable = dedupeVariable(variable, seen);
                node.setVariableName(variable);
            } else {
                result.addError("Duplicate variable name: " + variable);
            }
        }
        if (node.getChildren() == null) {
            return;
        }
        for (DocNode child : node.getChildren()) {
            validateNode(child, seen, result);
        }
    }

    private static String dedupeVariable(String base, Set<String> seen) {
        int idx = 2;
        String candidate = base + "_" + idx;
        while (!seen.add(candidate)) {
            idx++;
            candidate = base + "_" + idx;
        }
        return candidate;
    }
}
