/*
 * Copyright © 2024 PCI Technology Group Co.,Ltd. All Rights Reserved.
 * Site: http://www.pcitech.com/
 * Address：PCI Intelligent Building, No.2 Xincen Fourth Road, Tianhe District, Guangzhou，China（Zip code：510653）
 */
package org.gensokyo.plugin.easydoc.dto;

import com.intellij.database.model.DasColumn;
import com.intellij.database.model.DataType;
import com.intellij.database.util.DasUtil;
import lombok.Data;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Method;
import java.util.Objects;

/**
 * 列对象
 *
 * @author Gensokyo V.L.
 * @version 1.0.0
 * @since 2024/6/6 , Version 1.0.0
 */
@Data
public class ColumnDTO implements Item<ColumnDTO> {

    public ColumnDTO() {
    }

    public ColumnDTO(DasColumn column) {
        this.das = column;
        this.name = column.getName();
        this.comment = resolveColumnComment(column);
        DataType dataType = column.getDasType().toDataType();
        this.type = dataType.typeName;
        this.length = dataType.getLength();
        this.isQuoted = column.isQuoted();
        this.defaultValue = Objects.toString(column.getDefault(), "");
        this.isNotNull = column.isNotNull();
        this.isPrimaryKey = DasUtil.isPrimary(column);
        this.isIndex = DasUtil.isIndexColumn(column);
        this.isForeign = DasUtil.isForeign(column);
        this.isAutoGenerated = DasUtil.isAutoGenerated(column);
        this.isAuto = DasUtil.isAuto(column);
        this.isComputed = DasUtil.isComputed(column);
        this.tableName = column.getTableName();
    }

    private static String resolveColumnComment(DasColumn column) {
        String primary = StringUtils.trimToEmpty(Objects.toString(column.getComment(), ""));
        if (StringUtils.isNotBlank(primary)) {
            return primary;
        }
        return StringUtils.trimToEmpty(firstStringFromReflect(column,
                "getRemarks", "getRemark", "getDescription", "getCommentText"));
    }

    private static String firstStringFromReflect(Object target, String... methodNames) {
        for (String name : methodNames) {
            try {
                Method m = target.getClass().getMethod(name);
                if (m.getParameterCount() != 0) {
                    continue;
                }
                m.trySetAccessible();
                Object r = m.invoke(target);
                if (r == null) {
                    continue;
                }
                String s = StringUtils.trimToEmpty(String.valueOf(r));
                if (StringUtils.isNotBlank(s)) {
                    return s;
                }
            } catch (ReflectiveOperationException | SecurityException ignored) {
                // try next method name
            }
        }
        return "";
    }

    private DasColumn das;

    private String name;

    private String comment;

    private String type;

    private int length;

    private boolean isQuoted;

    private String defaultValue;

    private boolean isNotNull;

    private boolean isPrimaryKey;

    private boolean isIndex;

    private boolean isForeign;

    private boolean isAutoGenerated;

    private boolean isAuto;

    private boolean isComputed;

    private String tableName;

    public void prepareForRender() {
        this.das = null;
    }
}
